palette:
  base: '#ef005d'
  link: '#ef005d'
  accent1: '#ffbc00'
  accent2: '#0085ca'
  text: '#333333'
  headings: '#000000'
  footer: '#f2f2f2'
  footertext: '#333333'
  secheader: '#ffbc00'
  secheadertext: '#ffffff'
  card: '#ffffff'
  cardtext: '#000000'
  header: '#000000'
  headertext: '#ffffff'
  headerside: '#efefef'
  headersidetext: '#333333'
  pagetitle: '#ffffff'
  pagetitletext: '#000000'
  graylight: '#bbbbbb'
  graylighter: '#f2f2f2'
  silver: '#f2f2f2'
  body: '#efefef'
logo: 'public://color/dxpr_theme-f35fe068/logo.svg'
stylesheets:
  - 'public://color/dxpr_theme-f35fe068/footer-menu.css'
  - 'public://color/dxpr_theme-f35fe068/forms.css'
  - 'public://color/dxpr_theme-f35fe068/layout.css'
  - 'public://color/dxpr_theme-f35fe068/page-title.css'
  - 'public://color/dxpr_theme-f35fe068/typography.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-full-screen-search.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-header.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-header--top.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-header--side.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-header--mobile.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-secondary-header.css'
  - 'public://color/dxpr_theme-f35fe068/bootstrap-3.css'
  - 'public://color/dxpr_theme-f35fe068/bootstrap-theme.css'
  - 'public://color/dxpr_theme-f35fe068/jquery-ui.css'
  - 'public://color/dxpr_theme-f35fe068/drupal-breadcrumbs.css'
  - 'public://color/dxpr_theme-f35fe068/drupal-comments.css'
  - 'public://color/dxpr_theme-f35fe068/drupal-pager.css'
  - 'public://color/dxpr_theme-f35fe068/drupal-webform.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-builder.css'
  - 'public://color/dxpr_theme-f35fe068/helper-classes.css'
files:
  - 'public://color/dxpr_theme-f35fe068/logo.svg'
  - 'public://color/dxpr_theme-f35fe068/footer-menu.css'
  - 'public://color/dxpr_theme-f35fe068/forms.css'
  - 'public://color/dxpr_theme-f35fe068/layout.css'
  - 'public://color/dxpr_theme-f35fe068/page-title.css'
  - 'public://color/dxpr_theme-f35fe068/typography.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-full-screen-search.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-header.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-header--top.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-header--side.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-header--mobile.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-secondary-header.css'
  - 'public://color/dxpr_theme-f35fe068/bootstrap-3.css'
  - 'public://color/dxpr_theme-f35fe068/bootstrap-theme.css'
  - 'public://color/dxpr_theme-f35fe068/jquery-ui.css'
  - 'public://color/dxpr_theme-f35fe068/drupal-breadcrumbs.css'
  - 'public://color/dxpr_theme-f35fe068/drupal-comments.css'
  - 'public://color/dxpr_theme-f35fe068/drupal-pager.css'
  - 'public://color/dxpr_theme-f35fe068/drupal-webform.css'
  - 'public://color/dxpr_theme-f35fe068/dxpr-theme-builder.css'
  - 'public://color/dxpr_theme-f35fe068/helper-classes.css'
