_core:
  default_config_hash: 3mgYDspyj5REgG6ooA1izlcMzEs34kHPFUOMIXeDOco
entity_type_groups:
  node:
    article:
      basic: basic
      advanced: advanced
    page:
      basic: basic
      advanced: advanced
separator: ','
tag_trim_method: afterValue
use_maxlength: true
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
  metatag_maxlength_og_site_name: null
  metatag_maxlength_og_title: null
  metatag_maxlength_og_description: null
  metatag_maxlength_dcterms_title: null
  metatag_maxlength_dcterms_description: null
  metatag_maxlength_pinterest_description: null
  metatag_maxlength_twitter_cards_description: null
  metatag_maxlength_twitter_cards_title: null
tag_scroll_max_height: ''
