_core:
  default_config_hash: RePADAH4yHzDAKh-gEsDxPFK9hQe32l4p4t8Cqryww8
langcode: en
uuid: 075ee5a0-6e36-4901-af7f-a17b0a3c7876
name: 'Fog & Fireflies'
mail: admin@fogandfireflies.com
slogan: 'An author site for TH Lehnen'
page:
  403: /403
  404: /404
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
