_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: be6b18ab-1b58-42cc-806a-833c46c23b7a
name: 'Aspen & Thorn Press'
mail: admin@fogandfireflies.com
slogan: 'Publishers of Fog & Fireflies by T.H. Lehnen'
page:
  403: ''
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
