_core:
  default_config_hash: RePADAH4yHzDAKh-gEsDxPFK9hQe32l4p4t8Cqryww8
langcode: en
uuid: b1a74e1f-64f0-4cdd-9f5a-05316c30a84b
name: 'Fog & Fireflies'
mail: admin@fogandfireflies.com
slogan: 'An author site for TH Lehnen'
page:
  403: /403
  404: /404
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
